name: Build n Release Synology Custom Packages

on:
  release:
    types: [published]

  workflow_dispatch:
    
jobs:
    build-spk:
        name: Build Package
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                dsm: ['7.0','7.1','7.2']
                arch: ['kvmx64']
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Synology Package Builder Github Action
              uses: tomgrv/synology-package-builder@v1.3.0
              with:
                  dsm: ${{ matrix.dsm }}
                  arch: ${{ matrix.arch }}
                  projects: Changepanelsize:./ChangePanelSize
                  output: ./dist
            - name: Remove debug spk and rename package
              run: |
                rm ./dist/Changepanelsize-x86_64-1.0.0_debug.spk
                mv ./dist/Changepanelsize-x86_64-1.0.0.spk ./dist/Changepanelsize-x86_64-1.0.0-${{ matrix.dsm }}.spk
                ls -l ./dist
            - name: Upload Package
              uses: actions/upload-artifact@v4
              with:
                  name: packages-${{ matrix.dsm }}-${{ matrix.arch }}
                  path: ./dist/*.spk
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ inputs.version }}
                files: |
                  ./dist/*.spk
