name: Build Synology Custom Packages

on:
  push:
    branches:
      - develop
      - hotfix/*
      - release/*
  workflow_dispatch:

jobs:
  build-packages:
    name: Build all mypkg packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dsm: [7.2]
        arch: [apollolake, geminilake, avoton]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all mypkg packages
        id: findpkgs
        run: |
          echo "PACKAGES<<EOF" >> $GITHUB_ENV
          find mypkg -mindepth 1 -maxdepth 1 -type d | sed 's|^|./|' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build each package with tomgrv action
        run: |
          mkdir -p dist
          IFS=$'\n'
          for pkg in $PACKAGES; do
            alias=$(basename "$pkg")
            echo "Building $alias (DSM ${{ matrix.dsm }}, arch ${{ matrix.arch }})"
            echo "$pkg:$pkg" > projects.txt
            gh workflow run build-packages.yml \
              --field projects="$(cat projects.txt)" \
              --field dsm=${{ matrix.dsm }} \
              --field arch=${{ matrix.arch }} \
              --field output=dist
          done
        shell: bash

      - name: Synology Package Builder Github Action
        uses: tomgrv/synology-package-builder@v1.3.0
        with:
          dsm: ${{ matrix.dsm }}
          arch: ${{ matrix.arch }}
          projects: |
            ./src/web_package_example
            # 필요한 패키지 디렉토리를 여기에 추가하세요
          output: ./dist

      - name: Upload SPK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: synology-packages-${{ matrix.dsm }}-${{ matrix.arch }}
          path: ./dist/*.spk
