name: Build Synology SPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-spk:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

     # 1) Override the runner's tar to skip device‐node creation
      - name: Shim tar to ignore devices
        run: |
          sudo mv /usr/bin/tar /usr/bin/tar.orig
          echo '#!/usr/bin/env bash' | sudo tee /usr/bin/tar
          echo 'exec /usr/bin/tar.orig --no-devices "$@"' | sudo tee -a /usr/bin/tar
          sudo chmod +x /usr/bin/tar          
          
      - name: Set up DSM build environment
        working-directory: ./pkgscripts-ng
        run: |
          # DSM 7.2 chroot 환경 배포 (apollolake 플랫폼)
          ./EnvDeploy -v 7.2 -p apollolake

      - name: Prepare source directory
        run: |
          # Toolkit chroot 루트 경로에 패키지 소스 복사
          BUILD_ROOT=./pkgscripts-ng/build_env/ds.noarch-7.2/root
          mkdir -p ${BUILD_ROOT}/source/ChangePanelSize
          cp -R DSM7.2/mypkg/change_panel_size/* ${BUILD_ROOT}/source/ChangePanelSize/

      - name: Build .spk package
        working-directory: ./pkgscripts-ng
        run: |
          # SPK 빌드 (패키지 아키텍처는 noarch)
          ./PkgCreate.py -v 7.2 -p apollolake -c ChangePanelSize --package-arch noarch      

      - name: Upload SPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: change_panel_size-spk
          path: pkgscripts-ng/result_spk/*.spk
