name: Build n Release Synology Smart Info

on:
  release:
    types: [published]

  workflow_dispatch:
    
jobs:
    build-spk:
        name: Build Package
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                #dsm: ['7.2']
                arch: ['kvmx64']
                dsm: ['7.0','7.1','7.2']
                #arch: ['epyc7002','v1000nk','r1000nk','geminilakenk','broadwellnk','cedarview','broadwell','broadwellnkv2','broadwellntbap','purley','bromolow','avoton','braswell','grantley','denverton','apollolake','r1000','v1000','geminilake']
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Synology Package Builder Github Action
              uses: tomgrv/synology-package-builder@v1.3.0
              with:
                  dsm: ${{ matrix.dsm }}
                  arch: ${{ matrix.arch }}
                  projects: SynoSmartInfo:./SynoSmartInfo
                  output: ./dist
            #- name: Remove debug spk and rename package
            #  run: |
            #    rm ./dist/Synosmartinfo-x86_64-1.0.0_debug.spk
            #    mv ./dist/Synosmartinfo-x86_64-1.0.0.spk ./dist/Synosmartinfo-x86_64-1.0.0-${{ matrix.dsm }}-${{ matrix.arch }}.spk
            #    ls -l ./dist
            - name: Upload Package
              uses: actions/upload-artifact@v4
              with:
                  name: packages-${{ matrix.dsm }}-${{ matrix.arch }}
                  path: ./dist/*.spk
            #- name: Release
            #  uses: softprops/action-gh-release@v2
            #  with:
            #    tag_name: ${{ inputs.version }}
            #    files: |
            #      ./dist/*.spk
