# @format

on:
    push:
        branches:
            - develop
            - hotfix/*
            - release/*

jobs:
    test-action:
        name: Test package creation
        runs-on: ubuntu-latest
        env:
            project:
        strategy:
            fail-fast: true
            max-parallel: 1
            matrix:
                dsm: ['7.0']
                arch: ['geminilake', 'avoton']
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Prepare test packages
              run: |
                  rm -rf ./src && git clone https://github.com/SynologyOpenSource/ExamplePackages ./src && ls -l . && pwd
              shell: sh
            - id: build
              name: Build Package with local action
              uses: ./
              with:
                  dsm: ${{ matrix.dsm }}
                  arch: ${{ matrix.arch }}
                  projects: |
                      ./src/web_package_example
                  output: ./dist
