# @format

on:
    push:
        branches:
            - main
            - develop
            - 'release/**'
            - 'feature/**'

jobs:
    test-action:
        name: Test package creation
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                dsm: ['7.0']
                arch: ['geminilake', 'avoton']
                projects:
                    [
                        './src/web_package_example',
                        './src/ExamplePackage',
                        './ghr',
                    ]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Prepare test packages
              run: |
                  rm -rf src && git clone https://github.com/SynologyOpenSource/ExamplePackages src
            - name: Build Package with local action
              uses: ./
              with:
                  dsm: ${{ matrix.dsm }}
                  arch: ${{ matrix.arch }}
                  projects: ${{ matrix.projects }}
            - name: Upload Package
              uses: actions/upload-artifact@v4
              with:
                  name: packages-${{ matrix.dsm }}-${{ matrix.arch }}
                  path: ./bin/*.spk
    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: test-action
        if: startsWith(github.ref, 'refs/tags/')
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download Package Artifact
              uses: actions/download-artifact@v4
              with:
                  path: ./bin
            - name: List Retrieved Artifacts
              run: rsync -av ./bin/*/*/ ./output/
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./output/*.spk
                  draft: false
                  prerelease: false
